-- begin ASSETMANAGEMENT_ADD__ASSET
create unique index IDX_ASSETMANAGEMENT_ADD__ASSET_UNIQ_SERIAL_NUMBER on ASSETMANAGEMENT_ADD__ASSET (SERIAL_NUMBER) ^
create unique index IDX_ASSETMANAGEMENT_ADD__ASSET_UNIQ_ASSET__ID on ASSETMANAGEMENT_ADD__ASSET (ASSET__ID) ^
-- end ASSETMANAGEMENT_ADD__ASSET
-- begin ASSETMANAGEMENT_REQUEST
alter table ASSETMANAGEMENT_REQUEST add constraint FK_ASSETMANAGEMENT_REQUEST_CLIENT foreign key (CLIENT_ID) references SEC_USER(ID)^
alter table ASSETMANAGEMENT_REQUEST add constraint FK_ASSETMANAGEMENT_REQUEST_ASSET foreign key (ASSET_ID) references ASSETMANAGEMENT_ADD__ASSET(ID)^
create index IDX_ASSETMANAGEMENT_REQUEST_CLIENT on ASSETMANAGEMENT_REQUEST (CLIENT_ID)^
create index IDX_ASSETMANAGEMENT_REQUEST_ASSET on ASSETMANAGEMENT_REQUEST (ASSET_ID)^
-- end ASSETMANAGEMENT_REQUEST
-- begin ASSETMANAGEMENT_ORDER__STATUS
alter table ASSETMANAGEMENT_ORDER__STATUS add constraint FK_ASSETMANAGEMENT_ORDER__STATUS_REQUESTED_ASSET foreign key (REQUESTED_ASSET_ID) references ASSETMANAGEMENT_REQUEST(ID)^
create index IDX_ASSETMANAGEMENT_ORDER__STATUS_REQUESTED_ASSET on ASSETMANAGEMENT_ORDER__STATUS (REQUESTED_ASSET_ID)^
-- end ASSETMANAGEMENT_ORDER__STATUS
