alter table ASSETMANAGEMENT_REQUEST add constraint FK_ASSETMANAGEMENT_REQUEST_ASSET foreign key (ASSET_ID) references ASSETMANAGEMENT_ADD__ASSET(ID);
create index IDX_ASSETMANAGEMENT_REQUEST_ASSET on ASSETMANAGEMENT_REQUEST (ASSET_ID);
