alter table ASSETMANAGEMENT_REQUEST add constraint FK_ASSETMANAGEMENT_REQUEST_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_ASSETMANAGEMENT_REQUEST_USER on ASSETMANAGEMENT_REQUEST (USER_ID);
