alter table ASSETMANAGEMENT_REQUEST add constraint FK_ASSETMANAGEMENT_REQUEST_CLIENT foreign key (CLIENT_ID) references SEC_USER(ID);
create index IDX_ASSETMANAGEMENT_REQUEST_CLIENT on ASSETMANAGEMENT_REQUEST (CLIENT_ID);
